### ISSUE TITLE
Feature request | Add backup_ad_server

### ISSUE THREAD

**Issue by x09** [mdhowle/ansible-ad-inventory#8]
if **server** is down, try use **backup_server**

```
plugin: ad
server: server1
backup_server: server2
```

**Comment by mdhowle** [comment]
I added the ability to specify multiple servers in the `server` line. The plugin will try each server in order until it successfully returns.

```yaml
# This still works
server: dc1.example.com   

server: [dc1.example.com, dc2.example.com, dc3.example.com]

server:
  - dc1.example.com
  - dc2.example.com
  - dc3.example.com
```
